import React, { useState, useEffect } from 'react';
import {
  View,
    Text,
      TextInput,
        TouchableOpacity,
          StyleSheet,
            ActivityIndicator,
              KeyboardAvoidingView,
                Platform,
                } from 'react-native';
                import { useRouter } from 'expo-router';
                import { supabase } from '@/lib/supabase';

                export default function LoginScreen() {
                  const [input, setInput] = useState('');
                    const [password, setPassword] = useState('');
                      const [loading, setLoading] = useState(false);
                        const [error, setError] = useState('');
                          const router = useRouter();

                            // Check if user is already logged in
                              useEffect(() => {
                                  const checkIfLoggedIn = async () => {
                                        const { data: { session } } = await supabase.auth.getSession();
                                              if (session) {
                                                      router.replace('/(app)/overview');
                                                            }
                                                                };
                                                                    checkIfLoggedIn();
                                                                      }, []);

                                                                        const handleLogin = async () => {
                                                                            setError('');
                                                                                if (!input.trim() || !password.trim()) {
                                                                                      setError('Please enter email / Student ID and password');
                                                                                            return;
                                                                                                }

                                                                                                    setLoading(true);

                                                                                                        try {
                                                                                                              const isStudent = !input.includes('@');
                                                                                                                    const email = isStudent
                                                                                                                            ? `${input.trim().toLowerCase()}@student.school.local`
                                                                                                                                    : input.trim();

                                                                                                                                          const { data, error: authError } = await supabase.auth.signInWithPassword({
                                                                                                                                                  email,
                                                                                                                                                          password,
                                                                                                                                                                });

                                                                                                                                                                      if (authError || !data?.user) {
                                                                                                                                                                              setError(authError?.message || 'Login failed');
                                                                                                                                                                                      setLoading(false);
                                                                                                                                                                                              return;
                                                                                                                                                                                                    }

                                                                                                                                                                                                          // Get role
                                                                                                                                                                                                                const { data: role } = await supabase.rpc('current_user_role');

                                                                                                                                                                                                                      if (role && ['admin', 'teacher', 'student'].includes(role)) {
                                                                                                                                                                                                                              router.replace('/(app)/overview');
                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                            setError('No role assigned to this account');
                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                      } catch (err: any) {
                                                                                                                                                                                                                                                            setError(err.message || 'Something went wrong');
                                                                                                                                                                                                                                                                } finally {
                                                                                                                                                                                                                                                                      setLoading(false);
                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                  <KeyboardAvoidingView
                                                                                                                                                                                                                                                                                        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
                                                                                                                                                                                                                                                                                              style={styles.container}
                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                        <View style={styles.card}>
                                                                                                                                                                                                                                                                                                                <Text style={styles.title}>CampusOS</Text>
                                                                                                                                                                                                                                                                                                                        <Text style={styles.subtitle}>Secure Portal Access</Text>

                                                                                                                                                                                                                                                                                                                                <TextInput
                                                                                                                                                                                                                                                                                                                                          style={styles.input}
                                                                                                                                                                                                                                                                                                                                                    placeholder="Email or Student ID"
                                                                                                                                                                                                                                                                                                                                                              placeholderTextColor="#94a3b8"
                                                                                                                                                                                                                                                                                                                                                                        autoCapitalize="none"
                                                                                                                                                                                                                                                                                                                                                                                  value={input}
                                                                                                                                                                                                                                                                                                                                                                                            onChangeText={setInput}
                                                                                                                                                                                                                                                                                                                                                                                                    />

                                                                                                                                                                                                                                                                                                                                                                                                            <TextInput
                                                                                                                                                                                                                                                                                                                                                                                                                      style={styles.input}
                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholderTextColor="#94a3b8"
                                                                                                                                                                                                                                                                                                                                                                                                                                                    secureTextEntry
                                                                                                                                                                                                                                                                                                                                                                                                                                                              value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChangeText={setPassword}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {error ? <Text style={styles.error}>{error}</Text> : null}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <TouchableOpacity
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={[styles.button, loading && { opacity: 0.7 }]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onPress={handleLogin}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {loading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <ActivityIndicator color="#fff" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Text style={styles.buttonText}>Login to Portal</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </KeyboardAvoidingView>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  container: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          backgroundColor: '#f0f9ff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              justifyContent: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: 24,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      card: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          backgroundColor: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderRadius: 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  padding: 28,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      elevation: 5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          title: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontSize: 28,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontWeight: '800',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      color: '#0284c7',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              marginBottom: 6,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  subtitle: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: 15,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: '#64748b',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  marginBottom: 28,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      input: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderWidth: 1.5,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderColor: '#e2e8f0',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      padding: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              marginBottom: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  backgroundColor: '#f8fafc',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      button: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          backgroundColor: '#0284c7',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              paddingVertical: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  borderRadius: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginTop: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              buttonText: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontWeight: '700',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              error: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: '#dc2626',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize: 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          marginBottom: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              textAlign: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });